version: "3"
services:

  # Redis
  redis:
    build: docker/redis
    volumes:
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
    expose:
      - 6379
    ports:
      - 6379:6379

  # Redis-LRU
  redis-lru:
    build: docker/redis
    volumes:
      - ./docker/redis/redis-lru.conf:/usr/local/etc/redis/redis.conf
    expose:
      - 6379
    ports:
      - 6380:6379

  # Web
  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    volumes:
      - ./config/server.crt:/app/server.crt
      - ./config/server.key:/app/server.key
    expose:
      - 8080
    ports:
      - 8080:8080

  # Auth
  auth:
    build:
      context: .
      dockerfile: docker/auth/Dockerfile
    volumes:
      - ./config/server.crt:/app/server.crt
      - ./config/server.key:/app/server.key
    expose:
      - 8081
    ports:
      - 8081:8081
    links:
      - redis
      - redis-lru

  # Mapper
  mapper:
    build:
      context: .
      dockerfile: docker/mapper/Dockerfile
    volumes:
      - ./config/server.crt:/app/server.crt
      - ./config/server.key:/app/server.key
    expose:
      - 8082
    ports:
      - 8082:8082
    links:
      - redis
      - redis-lru
