version: 2

jobs:

  build:
    docker:
      - image: circleci/golang:1.14.4
        environment:
          GO111MODULE: "on"
    working_directory: /go/src/github.com/elojah/game_02
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: make tidy

  test:
    docker:
      - image: circleci/golang:1.14.4
    working_directory: /go/src/github.com/elojah/game_02
    steps:
      - checkout
      - run:
          name: Install linters
          command: curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s v1.27.0
      - run:
          name: Run unit
          command: make check
          environment:
            GO111MODULE: "on"
            CGO_ENABLED: 1

  deploy:
    docker:
      - image: circleci/golang:1.14.4
    steps:
      - checkout

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: master
