// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: sector.proto

package space

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import geometry "github.com/elojah/game_02/pkg/geometry"
import _ "github.com/gogo/protobuf/gogoproto"

import github_com_elojah_game_02_pkg_ulid "github.com/elojah/game_02/pkg/ulid"

import strings "strings"
import reflect "reflect"
import github_com_gogo_protobuf_sortkeys "github.com/gogo/protobuf/sortkeys"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type Sector struct {
	ID                   github_com_elojah_game_02_pkg_ulid.ID `protobuf:"bytes,1,opt,name=ID,json=iD,proto3,customtype=github.com/elojah/game_02/pkg/ulid.ID" json:"ID"`
	Dim                  geometry.Vec3                         `protobuf:"bytes,2,opt,name=Dim,json=dim" json:"Dim"`
	Adjacents            map[string]geometry.Vec3              `protobuf:"bytes,3,rep,name=Adjacents,json=adjacents" json:"Adjacents" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value"`
	TileMap              github_com_elojah_game_02_pkg_ulid.ID `protobuf:"bytes,4,opt,name=TileMap,json=tileMap,proto3,customtype=github.com/elojah/game_02/pkg/ulid.ID" json:"TileMap"`
	GraphicMap           []uint64                              `protobuf:"varint,5,rep,packed,name=GraphicMap,json=graphicMap" json:"GraphicMap,omitempty"`
	CollisionMap         []uint64                              `protobuf:"varint,6,rep,packed,name=CollisionMap,json=collisionMap" json:"CollisionMap,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                              `json:"-"`
	XXX_sizecache        int32                                 `json:"-"`
}

func (m *Sector) Reset()      { *m = Sector{} }
func (*Sector) ProtoMessage() {}
func (*Sector) Descriptor() ([]byte, []int) {
	return fileDescriptor_sector_f01df985344d04c3, []int{0}
}
func (m *Sector) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Sector) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Sector.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *Sector) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Sector.Merge(dst, src)
}
func (m *Sector) XXX_Size() int {
	return m.Size()
}
func (m *Sector) XXX_DiscardUnknown() {
	xxx_messageInfo_Sector.DiscardUnknown(m)
}

var xxx_messageInfo_Sector proto.InternalMessageInfo

func (m *Sector) GetDim() geometry.Vec3 {
	if m != nil {
		return m.Dim
	}
	return geometry.Vec3{}
}

func (m *Sector) GetAdjacents() map[string]geometry.Vec3 {
	if m != nil {
		return m.Adjacents
	}
	return nil
}

func (m *Sector) GetGraphicMap() []uint64 {
	if m != nil {
		return m.GraphicMap
	}
	return nil
}

func (m *Sector) GetCollisionMap() []uint64 {
	if m != nil {
		return m.CollisionMap
	}
	return nil
}

func init() {
	proto.RegisterType((*Sector)(nil), "space.Sector")
	proto.RegisterMapType((map[string]geometry.Vec3)(nil), "space.Sector.AdjacentsEntry")
}
func (this *Sector) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Sector)
	if !ok {
		that2, ok := that.(Sector)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.ID.Equal(that1.ID) {
		return false
	}
	if !this.Dim.Equal(&that1.Dim) {
		return false
	}
	if len(this.Adjacents) != len(that1.Adjacents) {
		return false
	}
	for i := range this.Adjacents {
		a := this.Adjacents[i]
		b := that1.Adjacents[i]
		if !(&a).Equal(&b) {
			return false
		}
	}
	if !this.TileMap.Equal(that1.TileMap) {
		return false
	}
	if len(this.GraphicMap) != len(that1.GraphicMap) {
		return false
	}
	for i := range this.GraphicMap {
		if this.GraphicMap[i] != that1.GraphicMap[i] {
			return false
		}
	}
	if len(this.CollisionMap) != len(that1.CollisionMap) {
		return false
	}
	for i := range this.CollisionMap {
		if this.CollisionMap[i] != that1.CollisionMap[i] {
			return false
		}
	}
	return true
}
func (this *Sector) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 10)
	s = append(s, "&space.Sector{")
	s = append(s, "ID: "+fmt.Sprintf("%#v", this.ID)+",\n")
	s = append(s, "Dim: "+strings.Replace(this.Dim.GoString(), `&`, ``, 1)+",\n")
	keysForAdjacents := make([]string, 0, len(this.Adjacents))
	for k, _ := range this.Adjacents {
		keysForAdjacents = append(keysForAdjacents, k)
	}
	github_com_gogo_protobuf_sortkeys.Strings(keysForAdjacents)
	mapStringForAdjacents := "map[string]geometry.Vec3{"
	for _, k := range keysForAdjacents {
		mapStringForAdjacents += fmt.Sprintf("%#v: %#v,", k, this.Adjacents[k])
	}
	mapStringForAdjacents += "}"
	if this.Adjacents != nil {
		s = append(s, "Adjacents: "+mapStringForAdjacents+",\n")
	}
	s = append(s, "TileMap: "+fmt.Sprintf("%#v", this.TileMap)+",\n")
	s = append(s, "GraphicMap: "+fmt.Sprintf("%#v", this.GraphicMap)+",\n")
	s = append(s, "CollisionMap: "+fmt.Sprintf("%#v", this.CollisionMap)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func valueToGoStringSector(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}
func (m *Sector) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Sector) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0xa
	i++
	i = encodeVarintSector(dAtA, i, uint64(m.ID.Size()))
	n1, err := m.ID.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n1
	dAtA[i] = 0x12
	i++
	i = encodeVarintSector(dAtA, i, uint64(m.Dim.Size()))
	n2, err := m.Dim.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n2
	if len(m.Adjacents) > 0 {
		for k, _ := range m.Adjacents {
			dAtA[i] = 0x1a
			i++
			v := m.Adjacents[k]
			msgSize := 0
			if (&v) != nil {
				msgSize = (&v).Size()
				msgSize += 1 + sovSector(uint64(msgSize))
			}
			mapSize := 1 + len(k) + sovSector(uint64(len(k))) + msgSize
			i = encodeVarintSector(dAtA, i, uint64(mapSize))
			dAtA[i] = 0xa
			i++
			i = encodeVarintSector(dAtA, i, uint64(len(k)))
			i += copy(dAtA[i:], k)
			dAtA[i] = 0x12
			i++
			i = encodeVarintSector(dAtA, i, uint64((&v).Size()))
			n3, err := (&v).MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n3
		}
	}
	dAtA[i] = 0x22
	i++
	i = encodeVarintSector(dAtA, i, uint64(m.TileMap.Size()))
	n4, err := m.TileMap.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n4
	if len(m.GraphicMap) > 0 {
		dAtA6 := make([]byte, len(m.GraphicMap)*10)
		var j5 int
		for _, num := range m.GraphicMap {
			for num >= 1<<7 {
				dAtA6[j5] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j5++
			}
			dAtA6[j5] = uint8(num)
			j5++
		}
		dAtA[i] = 0x2a
		i++
		i = encodeVarintSector(dAtA, i, uint64(j5))
		i += copy(dAtA[i:], dAtA6[:j5])
	}
	if len(m.CollisionMap) > 0 {
		dAtA8 := make([]byte, len(m.CollisionMap)*10)
		var j7 int
		for _, num := range m.CollisionMap {
			for num >= 1<<7 {
				dAtA8[j7] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j7++
			}
			dAtA8[j7] = uint8(num)
			j7++
		}
		dAtA[i] = 0x32
		i++
		i = encodeVarintSector(dAtA, i, uint64(j7))
		i += copy(dAtA[i:], dAtA8[:j7])
	}
	return i, nil
}

func encodeVarintSector(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func NewPopulatedSector(r randySector, easy bool) *Sector {
	this := &Sector{}
	v1 := github_com_elojah_game_02_pkg_ulid.NewPopulatedID(r)
	this.ID = *v1
	v2 := geometry.NewPopulatedVec3(r, easy)
	this.Dim = *v2
	if r.Intn(10) != 0 {
		v3 := r.Intn(10)
		this.Adjacents = make(map[string]geometry.Vec3)
		for i := 0; i < v3; i++ {
			this.Adjacents[randStringSector(r)] = *geometry.NewPopulatedVec3(r, easy)
		}
	}
	v4 := github_com_elojah_game_02_pkg_ulid.NewPopulatedID(r)
	this.TileMap = *v4
	v5 := r.Intn(10)
	this.GraphicMap = make([]uint64, v5)
	for i := 0; i < v5; i++ {
		this.GraphicMap[i] = uint64(uint64(r.Uint32()))
	}
	v6 := r.Intn(10)
	this.CollisionMap = make([]uint64, v6)
	for i := 0; i < v6; i++ {
		this.CollisionMap[i] = uint64(uint64(r.Uint32()))
	}
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

type randySector interface {
	Float32() float32
	Float64() float64
	Int63() int64
	Int31() int32
	Uint32() uint32
	Intn(n int) int
}

func randUTF8RuneSector(r randySector) rune {
	ru := r.Intn(62)
	if ru < 10 {
		return rune(ru + 48)
	} else if ru < 36 {
		return rune(ru + 55)
	}
	return rune(ru + 61)
}
func randStringSector(r randySector) string {
	v7 := r.Intn(100)
	tmps := make([]rune, v7)
	for i := 0; i < v7; i++ {
		tmps[i] = randUTF8RuneSector(r)
	}
	return string(tmps)
}
func randUnrecognizedSector(r randySector, maxFieldNumber int) (dAtA []byte) {
	l := r.Intn(5)
	for i := 0; i < l; i++ {
		wire := r.Intn(4)
		if wire == 3 {
			wire = 5
		}
		fieldNumber := maxFieldNumber + r.Intn(100)
		dAtA = randFieldSector(dAtA, r, fieldNumber, wire)
	}
	return dAtA
}
func randFieldSector(dAtA []byte, r randySector, fieldNumber int, wire int) []byte {
	key := uint32(fieldNumber)<<3 | uint32(wire)
	switch wire {
	case 0:
		dAtA = encodeVarintPopulateSector(dAtA, uint64(key))
		v8 := r.Int63()
		if r.Intn(2) == 0 {
			v8 *= -1
		}
		dAtA = encodeVarintPopulateSector(dAtA, uint64(v8))
	case 1:
		dAtA = encodeVarintPopulateSector(dAtA, uint64(key))
		dAtA = append(dAtA, byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)))
	case 2:
		dAtA = encodeVarintPopulateSector(dAtA, uint64(key))
		ll := r.Intn(100)
		dAtA = encodeVarintPopulateSector(dAtA, uint64(ll))
		for j := 0; j < ll; j++ {
			dAtA = append(dAtA, byte(r.Intn(256)))
		}
	default:
		dAtA = encodeVarintPopulateSector(dAtA, uint64(key))
		dAtA = append(dAtA, byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)))
	}
	return dAtA
}
func encodeVarintPopulateSector(dAtA []byte, v uint64) []byte {
	for v >= 1<<7 {
		dAtA = append(dAtA, uint8(uint64(v)&0x7f|0x80))
		v >>= 7
	}
	dAtA = append(dAtA, uint8(v))
	return dAtA
}
func (m *Sector) Size() (n int) {
	var l int
	_ = l
	l = m.ID.Size()
	n += 1 + l + sovSector(uint64(l))
	l = m.Dim.Size()
	n += 1 + l + sovSector(uint64(l))
	if len(m.Adjacents) > 0 {
		for k, v := range m.Adjacents {
			_ = k
			_ = v
			l = v.Size()
			mapEntrySize := 1 + len(k) + sovSector(uint64(len(k))) + 1 + l + sovSector(uint64(l))
			n += mapEntrySize + 1 + sovSector(uint64(mapEntrySize))
		}
	}
	l = m.TileMap.Size()
	n += 1 + l + sovSector(uint64(l))
	if len(m.GraphicMap) > 0 {
		l = 0
		for _, e := range m.GraphicMap {
			l += sovSector(uint64(e))
		}
		n += 1 + sovSector(uint64(l)) + l
	}
	if len(m.CollisionMap) > 0 {
		l = 0
		for _, e := range m.CollisionMap {
			l += sovSector(uint64(e))
		}
		n += 1 + sovSector(uint64(l)) + l
	}
	return n
}

func sovSector(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozSector(x uint64) (n int) {
	return sovSector(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *Sector) String() string {
	if this == nil {
		return "nil"
	}
	keysForAdjacents := make([]string, 0, len(this.Adjacents))
	for k, _ := range this.Adjacents {
		keysForAdjacents = append(keysForAdjacents, k)
	}
	github_com_gogo_protobuf_sortkeys.Strings(keysForAdjacents)
	mapStringForAdjacents := "map[string]geometry.Vec3{"
	for _, k := range keysForAdjacents {
		mapStringForAdjacents += fmt.Sprintf("%v: %v,", k, this.Adjacents[k])
	}
	mapStringForAdjacents += "}"
	s := strings.Join([]string{`&Sector{`,
		`ID:` + fmt.Sprintf("%v", this.ID) + `,`,
		`Dim:` + strings.Replace(strings.Replace(this.Dim.String(), "Vec3", "geometry.Vec3", 1), `&`, ``, 1) + `,`,
		`Adjacents:` + mapStringForAdjacents + `,`,
		`TileMap:` + fmt.Sprintf("%v", this.TileMap) + `,`,
		`GraphicMap:` + fmt.Sprintf("%v", this.GraphicMap) + `,`,
		`CollisionMap:` + fmt.Sprintf("%v", this.CollisionMap) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringSector(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *Sector) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSector
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Sector: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Sector: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSector
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthSector
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ID.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Dim", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSector
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSector
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Dim.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Adjacents", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSector
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSector
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Adjacents == nil {
				m.Adjacents = make(map[string]geometry.Vec3)
			}
			var mapkey string
			mapvalue := &geometry.Vec3{}
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowSector
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowSector
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= (uint64(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthSector
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					var mapmsglen int
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowSector
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapmsglen |= (int(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					if mapmsglen < 0 {
						return ErrInvalidLengthSector
					}
					postmsgIndex := iNdEx + mapmsglen
					if mapmsglen < 0 {
						return ErrInvalidLengthSector
					}
					if postmsgIndex > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = &geometry.Vec3{}
					if err := mapvalue.Unmarshal(dAtA[iNdEx:postmsgIndex]); err != nil {
						return err
					}
					iNdEx = postmsgIndex
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipSector(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if skippy < 0 {
						return ErrInvalidLengthSector
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.Adjacents[mapkey] = *mapvalue
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TileMap", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSector
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthSector
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TileMap.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType == 0 {
				var v uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowSector
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.GraphicMap = append(m.GraphicMap, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowSector
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= (int(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthSector
				}
				postIndex := iNdEx + packedLen
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				for iNdEx < postIndex {
					var v uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowSector
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= (uint64(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.GraphicMap = append(m.GraphicMap, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field GraphicMap", wireType)
			}
		case 6:
			if wireType == 0 {
				var v uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowSector
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.CollisionMap = append(m.CollisionMap, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowSector
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= (int(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthSector
				}
				postIndex := iNdEx + packedLen
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				for iNdEx < postIndex {
					var v uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowSector
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= (uint64(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.CollisionMap = append(m.CollisionMap, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field CollisionMap", wireType)
			}
		default:
			iNdEx = preIndex
			skippy, err := skipSector(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSector
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipSector(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowSector
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSector
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSector
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthSector
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowSector
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipSector(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthSector = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowSector   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("sector.proto", fileDescriptor_sector_f01df985344d04c3) }

var fileDescriptor_sector_f01df985344d04c3 = []byte{
	// 394 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x51, 0x3f, 0xcb, 0xd3, 0x40,
	0x18, 0xcf, 0x25, 0xfd, 0x43, 0xaf, 0xa1, 0xc8, 0x4d, 0xa1, 0xc8, 0x35, 0x14, 0x95, 0x2c, 0x4d,
	0xa4, 0x45, 0x28, 0x82, 0xa0, 0x35, 0x52, 0x0a, 0xba, 0x44, 0x71, 0x95, 0x6b, 0x7a, 0xa6, 0xd7,
	0x26, 0xbd, 0x90, 0x3f, 0x42, 0x37, 0x3f, 0x80, 0x83, 0x1f, 0xc3, 0x8f, 0xe0, 0xe8, 0xd8, 0xb1,
	0xa3, 0x38, 0x14, 0x73, 0x2e, 0x8e, 0x1d, 0x1d, 0x25, 0x17, 0x0d, 0x7d, 0xe1, 0xe5, 0x1d, 0xde,
	0xed, 0x79, 0x9e, 0xdf, 0x9f, 0xe7, 0x77, 0xcf, 0x41, 0x3d, 0xa5, 0x7e, 0xc6, 0x13, 0x3b, 0x4e,
	0x78, 0xc6, 0x51, 0x33, 0x8d, 0x89, 0x4f, 0xfb, 0xa3, 0x80, 0x65, 0xeb, 0x7c, 0x69, 0xfb, 0x3c,
	0x72, 0x02, 0x1e, 0x70, 0x47, 0xa2, 0xcb, 0xfc, 0xbd, 0xec, 0x64, 0x23, 0xab, 0x4a, 0xd5, 0x7f,
	0x74, 0x41, 0xa7, 0x21, 0xdf, 0x90, 0xb5, 0x13, 0x90, 0x88, 0xbe, 0x7b, 0x38, 0x76, 0xe2, 0x6d,
	0xe0, 0x04, 0x94, 0x47, 0x34, 0x4b, 0xf6, 0x75, 0x51, 0xc9, 0x86, 0x9f, 0x34, 0xd8, 0x7a, 0x2d,
	0xb7, 0xa3, 0x27, 0x50, 0x5d, 0xb8, 0x06, 0x30, 0x81, 0xa5, 0xcf, 0x46, 0x87, 0xd3, 0x40, 0xf9,
	0x71, 0x1a, 0xdc, 0xbf, 0xd9, 0x35, 0x0f, 0xd9, 0xca, 0x5e, 0xb8, 0x9e, 0xca, 0x5c, 0xf4, 0x00,
	0x6a, 0x2e, 0x8b, 0x0c, 0xd5, 0x04, 0x56, 0x77, 0xdc, 0xb3, 0xeb, 0x3d, 0x6f, 0xa9, 0x3f, 0x99,
	0x35, 0x4a, 0x3f, 0x4f, 0x5b, 0xb1, 0x08, 0x3d, 0x85, 0x9d, 0x67, 0xab, 0x0d, 0xf1, 0xe9, 0x2e,
	0x4b, 0x0d, 0xcd, 0xd4, 0xac, 0xee, 0xf8, 0xae, 0x2d, 0x9f, 0x6c, 0x57, 0x41, 0xec, 0x1a, 0x7e,
	0xb1, 0xcb, 0x92, 0xfd, 0x3f, 0x6d, 0x87, 0xfc, 0x9f, 0xa2, 0x39, 0x6c, 0xbf, 0x61, 0x21, 0x7d,
	0x45, 0x62, 0xa3, 0x71, 0x9b, 0xb4, 0xed, 0xac, 0x52, 0x23, 0x0c, 0xe1, 0x3c, 0x21, 0xf1, 0x9a,
	0xf9, 0xa5, 0x57, 0xd3, 0xd4, 0xac, 0x86, 0x07, 0x83, 0x7a, 0x82, 0x86, 0x50, 0x7f, 0xce, 0xc3,
	0x90, 0xa5, 0x8c, 0xef, 0x4a, 0x46, 0x4b, 0x32, 0x74, 0xff, 0x62, 0xd6, 0x7f, 0x09, 0x7b, 0x57,
	0xf3, 0xa2, 0x3b, 0x50, 0xdb, 0xd2, 0xbd, 0x3c, 0x64, 0xc7, 0x2b, 0x4b, 0x74, 0x0f, 0x36, 0x3f,
	0x90, 0x30, 0xa7, 0xd7, 0x1f, 0xc7, 0xab, 0xc0, 0xc7, 0xea, 0x14, 0xcc, 0xa6, 0xc7, 0x02, 0x2b,
	0xdf, 0x0b, 0xac, 0x9c, 0x0b, 0x0c, 0xfe, 0x14, 0x18, 0x7c, 0x14, 0x18, 0x7c, 0x11, 0x18, 0x7c,
	0x15, 0x18, 0x7c, 0x13, 0x18, 0x1c, 0x04, 0x06, 0x47, 0x81, 0xc1, 0x4f, 0x81, 0xc1, 0x6f, 0x81,
	0x95, 0xb3, 0xc0, 0xe0, 0xf3, 0x2f, 0xac, 0x2c, 0x5b, 0xf2, 0x3f, 0x27, 0x7f, 0x03, 0x00, 0x00,
	0xff, 0xff, 0x6a, 0x3b, 0xe6, 0xd1, 0x4c, 0x02, 0x00, 0x00,
}
